language: python
arch:
  - AMD64
  - ppc64le
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true

install:
  - pip install --upgrade pip
  - pip install poetry
  - cd $TRAVIS_BUILD_DIR && make setup
  - pip install coveralls

script: make ci_test

after_success:
  coveralls
